version: 2.1

jobs:
  test_playwright:
    docker:
      - image: mcr.microsoft.com/playwright

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm ci

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm install
      - run: npm run pw:chrome:run
      - run: npm run pw:firefox:run
      - run: npm run pw:webkit:run

  test_cypress:
    environment:
      CYPRESS_USER_EMAIL: $USER_EMAIL
      CYPRESS_USER_PASSWORD: $USER_PASSWORD
      CYPRESS_API_URL: $API_URL
    docker:
      - image: cypress/base:12

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm ci

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm install
      - run: npm run cy:electron:desktop:run
      - run: npm run cy:electron:mobile:run

workflows:
  tests:
    jobs:
      - test_cypress
