version: 2.1
orbs:
  cypress: cypress-io/cypress@2.2.0

jobs:
  build:
    docker:
      - image: cypress/base:12

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm ci

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # we need to install CircleCI CLI tool
      # to run the "manual" tests
      - run: npm install
      - run: npm run cy:electron:desktop:run
      - run: npm run cy:electron:mobile:run

workflows:
  orb_tests:
    jobs:
      - build
